// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwkT3OBbBAVfMYIzhhsUAuzoFWfO3QVAA',
    appId: '1:728301094620:web:d7c1df572c869846e1d619',
    messagingSenderId: '728301094620',
    projectId: 'test-notification-fireba-b789a',
    authDomain: 'test-notification-fireba-b789a.firebaseapp.com',
    storageBucket: 'test-notification-fireba-b789a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTe-rgC5lNlpJefPVQfe6aaWA2pqazc7g',
    appId: '1:728301094620:android:ba590693c61a453fe1d619',
    messagingSenderId: '728301094620',
    projectId: 'test-notification-fireba-b789a',
    storageBucket: 'test-notification-fireba-b789a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGhsUvq7U_EcxvI34qwG38srVwczW2dE4',
    appId: '1:728301094620:ios:68ae9e93b5b741dee1d619',
    messagingSenderId: '728301094620',
    projectId: 'test-notification-fireba-b789a',
    storageBucket: 'test-notification-fireba-b789a.firebasestorage.app',
    iosBundleId: 'com.example.testNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGhsUvq7U_EcxvI34qwG38srVwczW2dE4',
    appId: '1:728301094620:ios:7a56da0875122bcbe1d619',
    messagingSenderId: '728301094620',
    projectId: 'test-notification-fireba-b789a',
    storageBucket: 'test-notification-fireba-b789a.firebasestorage.app',
    iosBundleId: 'com.example.testNotification2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwkT3OBbBAVfMYIzhhsUAuzoFWfO3QVAA',
    appId: '1:728301094620:web:81760779c2f92108e1d619',
    messagingSenderId: '728301094620',
    projectId: 'test-notification-fireba-b789a',
    authDomain: 'test-notification-fireba-b789a.firebaseapp.com',
    storageBucket: 'test-notification-fireba-b789a.firebasestorage.app',
  );
}
